version: 2.1
orbs:
  cypress: cypress-io/cypress@1.6.0
workflows:
  build:
    jobs:
      - cypress/run:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"
          yarn: true
